using TELERADIOLOGY.Application.Features.DoctorSignatures.CreateDoctorSignature;

namespace TELERADIOLOGY.Application.Features.DoctorSignatures.UpdateDoctorSignature;

public sealed class UpdateDoctorSignatureValidator:CreateDoctorSignatureValidator
{
}
